export const PATCH_NOTES = [
  {
    version: 'v0.13.0',
    date: '2026-03-07',
    title: 'Shared UI Primitive 도입(T7) + 핵심 화면 치환',
    summary: 'Button/Card/Badge/IconButton 공통 컴포넌트를 도입하고 핵심 기능 화면에 점진 적용해 스타일 중복을 줄였습니다.',
    focus: [
      '반복되는 `ui-btn/ui-panel` 클래스 사용을 공통 컴포넌트로 수렴해 유지보수 포인트 축소',
      '기존 동작은 유지하면서 렌더링 레이어만 치환하는 무동작 리팩토링 방식 유지',
      '카테고리/데이터복원/재배치/헤더/패치노트/리포트 카드의 버튼/카드 표현 일관화',
    ],
    improvements: [
      '`src/shared/ui`에 `Button`, `Card`, `Badge`, `IconButton`, `cn` 유틸 추가',
      'Header, PatchNotes, BrainDumpItem, WeeklyReportCard, DailyRecapCard에 공통 primitive 적용',
      'CategoryManagerModal, DataTransferModal, RescheduleAssistantModal에 공통 primitive 적용',
      '기존 E2E 스위트(30개) 통과로 회귀 없이 리팩토링 완료',
    ],
    validation: [
      'lint/build 통과',
      'E2E 전체 통과(30 passed)',
      '핵심 회귀: micro-interactions, category-manager, data-transfer, report-toggle, reschedule-assistant, patch-notes 통과',
    ],
  },
  {
    version: 'v0.12.9',
    date: '2026-03-07',
    title: '테마 토큰 통합 + 접근성 보강 + UI 회귀 테스트 확장',
    summary: '라이트/다크 일관성을 높이기 위해 semantic 토큰을 도입하고, ARIA 개선 및 레이아웃 회귀 테스트를 추가했습니다.',
    focus: [
      '공통 UI 클래스가 theme class와 충돌하지 않도록 색/서피스/보더를 semantic token 중심으로 정리',
      '토스트, 주간 스트립, 패치노트 토글, 플로팅 메뉴에 접근성 상태값(aria-live/expanded/current 등) 보강',
      '최근 조정한 UI(주간 gradient, 패치노트 토글 안정성, 30분 카드 정렬)를 E2E로 고정',
    ],
    improvements: [
      '`ui-panel`, `ui-panel-subtle`, `ui-btn-secondary`, `ui-btn-ghost`, `ui-input`, `ui-select`, `ui-modal-card`, `ui-glass-menu`를 semantic variable 기반으로 전환',
      '토스트 컨테이너 라이브 리전 적용 및 플로팅 메뉴/패치노트 토글 ARIA 상태 정보 추가',
      '새 E2E(`ui-layout-regression.spec.js`)로 핵심 레이아웃 회귀 자동 검출 추가',
    ],
    validation: [
      'lint/build 통과',
      'E2E 전체 통과(27 passed)',
      'E2E 추가 검증: ui-layout-regression, timer-mode, timeline-scale, patch-notes, weekly-strip 통과',
    ],
  },
  {
    version: 'v0.12.8',
    date: '2026-03-07',
    title: '다크 분리/주간 강조/패치노트 안정화/30분 카드 정렬',
    summary: '사용자 피드백 기반으로 다크 모드 경계, 주간 active 인지성, 패치노트 상세 레이아웃, 30분 카드 배치를 일괄 개선했습니다.',
    focus: [
      '다크 모드 브레인덤프 아이템이 배경과 섞여 보이는 문제를 tone contrast로 해소',
      '현재 날짜를 빠르게 인식할 수 있도록 주간 스트립 active 표현을 더 강하게 조정',
      '패치노트 모달의 라이트/다크 텍스트 충돌과 상세보기 토글 시 레이아웃 밀림을 방지',
      '30분 타임박스에서 태그 우측 쏠림을 제거하고 상태 배지와 재생 버튼을 같은 라인으로 정렬',
    ],
    improvements: [
      '브레인덤프 항목에 다크 전용 서피스 톤 + 미세 inset 라인 적용으로 항목 단위 분리 강화',
      '주간 날짜 스트립 active 카드에 gradient tone/ring/상단 하이라이트 라인 추가',
      '패치노트 모달을 slate 토큰으로 정리하고 토글 버튼 폭 고정으로 상세 영역 흔들림 제거',
      '타임박스 compact 레이아웃을 `#태그 -> 제목` 순서로 통일하고 상단 액션 라인을 재배치',
    ],
    validation: [
      'lint/build 통과',
      'E2E: micro-interactions, light-mode-guideline, weekly-strip, patch-notes, timer-mode, timeline-scale, timebox-dnd, skip-reason 통과',
    ],
  },
  {
    version: 'v0.12.7',
    date: '2026-03-07',
    title: 'UI 노이즈 다이어트 + 선택적 글래스모피즘 적용',
    summary: '사이드바/유틸 버튼 노이즈를 줄이고, 모달/FAB에만 전략적으로 글래스모피즘을 적용했습니다.',
    focus: [
      '핵심 콘텐츠 우선 원칙에 맞춰 보조 액션의 시각적 우선순위를 의도적으로 낮춤',
      '중첩 카드 구조의 답답함을 완화하고 라이트 모드에서 액티브 상태 대비를 명확히 강화',
    ],
    improvements: [
      '브레인덤프 액션 버튼(빅3/삭제)을 hover/focus 노출로 전환하고 빅3를 ghost 스타일로 약화',
      '주간/일간 리포트 접기 버튼을 아이콘 토글로 교체하고 유틸 버튼 강조도를 낮춤',
      '주간 계획 보드 내부 카드를 flat 톤(연한 배경+보더, no shadow)으로 재정의',
      '상단 날짜 스트립 gap 확대 + 비활성 날짜 투명도 강화 + 활성 날짜 강조',
      '빅3 빈 슬롯을 dashed border + 흐린 + 아이콘 힌트형 UI로 변경',
      '모달/FAB 메뉴에 선택적 글래스모피즘(라이트: white/40, 다크: slate-900/50) 적용',
    ],
    validation: ['lint/build/e2e 전체 회귀 통과 기준으로 반영'],
  },
  {
    version: 'v0.12.6',
    date: '2026-03-07',
    title: '라이트 모드 계층 분리 + 재생 버튼 우상단 정렬',
    summary: '정보 계층을 더 또렷하게 만들고 재생 버튼을 상태 배지 근처로 재배치해 겹침을 해소했습니다.',
    focus: [
      '라이트 모드에서 중요 카드와 컨테이너 레벨이 섞여 보이는 문제를 톤 단계로 분리',
      '타임박스 재생 버튼이 텍스트와 충돌하지 않도록 액션 영역을 우상단에 고정',
    ],
    improvements: [
      '앱 레이아웃 컨테이너(좌/우 패널)를 `ui-panel-subtle`로 낮추고 내부 카드를 상대적으로 강조',
      '`ui-panel-subtle` 라이트 톤을 `bg-slate-100`으로 조정해 중요/비중요 계층 대비 강화',
      '재생 버튼/완료 버튼을 우상단(상태 배지 주변)으로 이동하고 본문 패딩을 재조정해 겹침 제거',
    ],
    validation: ['Playwright 시각 점검 + lint/build/e2e 전체 회귀 통과'],
  },
  {
    version: 'v0.12.5',
    date: '2026-03-07',
    title: '라이트 모드 톤 계층 리팩토링',
    summary: 'Playwright 시각 점검 결과를 기반으로 라이트 모드 색상 계층을 가이드 토큰에 맞게 정렬했습니다.',
    focus: [
      '라이트 모드에서 어두운 패널이 남는 문제를 제거하고 Surface-over-Background 구조를 강화',
      '가이드 토큰(#F8F9FA/#FFFFFF/#1F1F1F/#444746)을 실제 렌더 결과와 일치시키는 데 집중',
    ],
    improvements: [
      'ui-panel/ui-panel-subtle/modal/app/header/nav의 라이트 기본 톤을 레이어드 화이트 구조로 재정의',
      'theme-light 토큰 오버라이드에 `bg-slate-50`, `bg-white`, `text-slate-*` 계층 추가',
      'Playwright E2E에 라이트 모드 토큰 검증 테스트 추가',
    ],
    validation: ['Playwright 풀스크린 시각 점검 + lint/build/e2e(전체) 통과'],
  },
  {
    version: 'v0.12.4',
    date: '2026-03-07',
    title: '타임라인 재생 버튼 시각 안정화',
    summary: '타임박스 재생 버튼을 중앙 정렬하고 태그 충돌을 해소해 조작성을 높였습니다.',
    focus: [
      '재생 버튼을 핵심 액션 트리거로 인지할 수 있도록 카드 중앙에 명확히 노출',
      '30분 카드에서 카테고리 태그와 버튼이 겹치지 않도록 텍스트 레이아웃 우선순위 조정',
    ],
    improvements: [
      '재생 버튼을 카드 수직 중앙으로 이동하고 좌측 액센트 바 기준 16px 이상 여백 확보',
      '컴팩트 카드에서 내용 텍스트 우선 배치 + 태그를 후순위 배지로 이동',
      '재생/완료 버튼 hover 시 scale-110 마이크로 인터랙션 추가',
    ],
    validation: ['lint/build/e2e(전체) 회귀 통과 기준으로 반영'],
  },
  {
    version: 'v0.12.3',
    date: '2026-03-07',
    title: 'Gemini 라이트 모드 레퍼런스 규칙 추가',
    summary: 'Front-end UX Guardian/가이드에 레이어드 화이트와 톤 기반 계층 원칙을 공식 반영했습니다.',
    focus: [
      '세션마다 라이트 모드 색상 톤이 흔들리지 않도록 참조 토큰을 고정',
      '선 기반 분할 대신 tonal elevation 원칙을 문서 상위 규칙으로 명시',
    ],
    improvements: [
      '.agents/FRONTEND_UX_GUARDIAN에 Gemini Light Mode Principle 섹션 추가',
      'AI_FRONTEND_GUIDE에 Surface-over-Background 요약 규칙 추가',
      '배경/카드/텍스트 색상 기준(#F8F9FA/#FFFFFF/#1F1F1F/#444746) 문서화',
    ],
    validation: ['문서 규칙 반영 + lint/build + patch-notes e2e + 전체 e2e 회귀 통과'],
  },
  {
    version: 'v0.12.2',
    date: '2026-03-07',
    title: '스켈레톤 로딩 + 삭제 마이크로 인터랙션',
    summary: '타임라인 인사이트 카드 로딩 전환을 부드럽게 만들고 브레인덤프 삭제 애니메이션을 추가했습니다.',
    focus: [
      '데이터 전환 시 카드가 갑자기 나타나는 감각을 줄이기 위해 스켈레톤 기반 전환 UX를 적용',
      '작은 삭제 동작에도 시각적 피드백이 남도록 slide-out 마이크로 인터랙션을 도입',
    ],
    improvements: [
      '날짜 이동 시 타임라인 상단 인사이트 영역에 스켈레톤 UI 표시 후 페이드 인 전환',
      '브레인덤프 항목 삭제 시 우측으로 밀리며 사라지는 220ms 애니메이션 적용',
      'E2E에 스켈레톤 표시/삭제 애니메이션 회귀 테스트 추가',
    ],
    validation: ['lint/build/e2e(전체) 통과 기준으로 반영'],
  },
  {
    version: 'v0.12.1',
    date: '2026-03-07',
    title: 'Front-end UX Guardian 규칙 도입',
    summary: '세션 간 UI 일관성을 위해 에이전트 기반 Look & Feel 규칙을 문서 체계에 통합했습니다.',
    focus: [
      '디자인 원칙이 세션마다 흔들리지 않도록 에이전트 문서와 기존 가이드를 동기화',
      'DnD/접근성 무결성을 보존하면서 시각적 미니멀 룰을 강제하는 기준 정립',
    ],
    improvements: [
      '.agents/FRONTEND_UX_GUARDIAN 문서 신설 및 SESSION_PLAYBOOK에 UI 작업 전 참조 규칙 추가',
      'AI_FRONTEND_GUIDE에 Interaction/Component 고정 규칙(브랜드 컬러, DnD 핸들러 보호) 확장',
      'README AI 협업 문서 목록에 Front-end UX Guardian 경로 연결',
    ],
    validation: ['문서 경로 연결 검증 + lint/build/e2e(패치노트/전체 회귀) 통과'],
  },
  {
    version: 'v0.12.0',
    date: '2026-03-07',
    title: '패치노트 운영 규칙 문서화',
    summary: '중요 변경마다 패치노트가 누락되지 않도록 세션 공통 규칙을 고정했습니다.',
    focus: [
      '새 세션이 들어와도 동일한 품질 기준으로 기록이 이어지도록 운영 절차를 표준화',
      '문서와 에이전트 지침이 서로 모순되지 않도록 단일 워크플로 경로를 추가',
    ],
    improvements: [
      '.agents/SESSION_PLAYBOOK에 중요 변경 시 패치노트 반영을 필수 단계로 추가',
      'docs에 PATCH_NOTES_WORKFLOW 문서 신설 및 DELIVERY/CONVENTIONS에 트리거 규칙 연결',
      'README AI 협업 문서 목록에 패치노트 워크플로 링크 추가',
    ],
    validation: [
      '문서 경로 연결 및 패치노트 모달 최신 버전(v0.12.0) 표시 확인',
      'lint/build/e2e 회귀 기준으로 문서 변경 절차를 유지',
    ],
  },
  {
    version: 'v0.11.0',
    date: '2026-03-07',
    title: '패치노트 상세보기 구조 도입',
    summary: '버전별 기록을 요약+상세로 분리해 추적성을 높였습니다.',
    focus: [
      '기능 추가보다 변경 의도와 품질 근거가 남도록 기록 포맷을 표준화',
      '히스토리 누락을 막기 위해 이전 릴리스까지 역추적 반영',
    ],
    improvements: [
      '패치노트를 버전 카드 + 상세보기(아코디언) UI로 개편',
      '`신경 쓴 부분 / 개선 사항 / 검증` 3단 섹션으로 상세 정보 구조화',
    ],
    validation: ['lint/build/e2e 회귀 통과를 기준으로 패치노트 반영'],
  },
  {
    version: 'v0.10.0',
    date: '2026-03-07',
    title: '라이트 모드 가독성 보강 + FAB 패치노트 진입',
    summary: '라이트 테마 대비를 높이고 FAB(플로팅 액션 버튼)에 패치노트 진입을 추가했습니다.',
    focus: [
      'WCAG 대비 기준(일반 텍스트 4.5:1)을 만족하는 텍스트/배경 대비 강화',
      '투명 배경(`bg-gray-900/60` 등)까지 라이트 톤으로 일관 치환',
    ],
    improvements: [
      '라이트 모드 색상 계층(배경/패널/텍스트/보더) 재정의',
      'FAB 메뉴에 `패치노트` 액션 및 모달 연결',
      '30분 카드에서 태그/사유 → 제목 순서로 정렬 통일',
    ],
    validation: ['E2E: theme-toggle, patch-notes, timeline-scale, skip-reason 통과'],
  },
  {
    version: 'v0.9.0',
    date: '2026-03-07',
    title: '실행력 고도화 세트',
    summary: '계획-실행 간 간극을 줄이기 위한 실행 기능들을 추가했습니다.',
    focus: [
      '실행 데이터(actualMinutes) 입력 마찰을 줄이기 위한 자동화',
      '미완료 일정 처리 시간을 단축하는 다음 날 배치 자동화',
    ],
    improvements: [
      '타이머 모드(시작/일시정지/완료) 및 자동 실제시간 반영',
      '자동 재배치 어시스턴트(다음 날 빈 슬롯 기반 일괄 적용)',
      '스킵 원인 기반 액션 템플릿 + 주간 계획 보드 프리뷰',
    ],
    validation: ['E2E: timer-mode, reschedule-assistant, skip-template-action 통과'],
  },
  {
    version: 'v0.8.0',
    date: '2026-03-06',
    title: '테마/조회 복원 + 스토리지 스키마 정비',
    summary: '새로고침 이후 컨텍스트를 잃지 않도록 복원 로직을 추가했습니다.',
    focus: [
      '사용자가 마지막으로 보던 날짜/슬롯에서 즉시 작업 재개 가능하도록 설계',
      '기존 저장 데이터와 호환되는 점진적 스키마 마이그레이션',
    ],
    improvements: [
      '다크/라이트 모드 토글 및 테마 저장',
      '최근 날짜/최근 슬롯 포커스 복원',
      '스토리지 schemaVersion v2 정규화',
    ],
    validation: ['E2E: theme-toggle, recent-restore 통과'],
  },
  {
    version: 'v0.7.0',
    date: '2026-03-06',
    title: '드래그 UX/리포트 확장',
    summary: '드래그 가시성과 주간 리포트를 강화했습니다.',
    focus: [
      '드롭 성공 예측 가능성을 높이기 위해 프리뷰 라인/가이드 도입',
      '주간 리포트의 해석력을 높이기 위해 원인 변화 데이터 추가',
    ],
    improvements: [
      '타임라인 드롭 프리뷰 라인 + 가이드 메시지',
      '주간/일간 리포트 접기-펼치기',
      '스킵 원인 변화(지난주 대비) 시각화',
    ],
    validation: ['E2E: inbox-to-timeline-dnd, report-toggle, weekly-report, skip-trend 통과'],
  },
  {
    version: 'v0.6.0',
    date: '2026-03-05',
    title: '핵심 플래너 루프 안정화',
    summary: '브레인덤프→빅3→타임라인 기본 루프를 안정화했습니다.',
    focus: [
      '드롭 좌표 오차와 겹침 충돌 같은 사용 중단 포인트 제거',
      '완료/스킵 데이터가 회고 카드에 반영되도록 흐름 정합성 확보',
    ],
    improvements: [
      '드래그앤드롭 슬롯 매핑 안정화 및 겹침 방지',
      '완료 모달, 스킵 사유 저장, 카드 비교 지표 반영',
      '카테고리 관리/데이터 내보내기-가져오기 도입',
    ],
    validation: ['E2E 회귀 기준 항목 전체 통과(당시 기준)'],
  },
]
